### ISSUE TITLE
Mobile Game Improvements

### ISSUE THREAD

**Issue by alexchrysovergis** [alexchrysovergis/alexchrysovergis.github.io#2]
There's an issue with the mobile version of the game which is accessible through the "Bored?" button on the website. When playing the game on a mobile device, the touch controls feel jittery and unresponsive.

### Objective

Enhance the touch controls on mobile devices to make them smoother and more responsive.

**Comment by SahilWMI** [comment]
Hey @alexchrysovergis ,

I just noticed that the slider on mobile keeps drifting to the right. I’d love to collaborate and help out if you need any assistance fixing it.

Just let me know.

**Comment by alexchrysovergis** [comment]
Hi @SahilWMI,  can you expand on what you mean by the slider "keeps drifting to the right"? Is there some kind of CSS overflow issue on mobile?

**Comment by SahilWMI** [comment]
> Hi @SahilWMI,  can you expand on what you mean by the slider "keeps drifting to the right"? Is there some kind of CSS overflow issue on mobile?

By "keeps drifting to the right," I mean that after interacting with the game on mobile, the paddle or controls don’t stop moving as expected. It might be related to how the touch events or layout are handled. I’ll be adjusting the code and will reach out to you on Discord for further discussion.


Thanks!

**Comment by alexchrysovergis** [comment]
It works as intended! Thank you so much for your valuable contribution and taking the time to fix the issue!
